language: python
python:
  - 3.6
  - nightly
script:
  - coverage run -m unittest discover # - python -m unittest discover if we don't need coverage
  - pylint --disable=R,C addme/
install:
  - pip install git+git://github.com/moj-analytical-services/dataengineeringutils.git#egg=etl_manager
  - pip install codecov
  - pip install coverage
  - pip install pylint
after_success:
  - codecov
